import logging
from sqlalchemy import event, text
from sqlalchemy.ext.asyncio import create_async_engine, async_sessionmaker, AsyncSession
from sqlalchemy.orm import DeclarativeBase
from app.config import get_settings

logger = logging.getLogger(__name__)


class Base(DeclarativeBase):
    pass


engine = create_async_engine(
    get_settings().database_url,
    echo=False,
    connect_args={"check_same_thread": False},
)


# Enable foreign key enforcement on every connection (required for ON DELETE CASCADE in SQLite)
@event.listens_for(engine.sync_engine, "connect")
def _set_sqlite_fk_pragma(dbapi_conn, connection_record):
    cursor = dbapi_conn.cursor()
    cursor.execute("PRAGMA foreign_keys=ON")
    cursor.close()

async_session = async_sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)


async def init_db():
    async with engine.begin() as conn:
        # Ranking rework 2026-05-15: session_results gains session_seq /
        # session_type / team_mode / effective_score / duration_s and a
        # new unique key (circuit, date, session_seq, driver). SQLite
        # can't ALTER a constraint and the rows are regenerated by the
        # ranking reprocess anyway, so drop+recreate is safe + simplest.
        # The unique constraint keeps the same name uq_session_result
        # (the old autoindex disappears with the dropped table).
        # MUST run BEFORE Base.metadata.create_all in this same connection:
        # it relies on create_all to rebuild both tables from the updated
        # models. Do NOT move it after create_all.
        try:
            res = await conn.execute(text("PRAGMA table_info(session_results)"))
            cols = {row[1] for row in res.fetchall()}
            if "session_seq" not in cols:
                await conn.execute(text("DROP TABLE IF EXISTS rating_history"))
                await conn.execute(text("DROP TABLE IF EXISTS session_results"))
                logger.info("Ranking rework: dropped rating_history + session_results for recreate")
        except Exception as e:
            logger.warning("Ranking rework migration check failed: %s", e)

        await conn.run_sync(Base.metadata.create_all)
        # Enable WAL mode for concurrent reads
        await conn.execute(text("PRAGMA journal_mode=WAL"))
        # Enable foreign key enforcement (required for ON DELETE CASCADE)
        await conn.execute(text("PRAGMA foreign_keys=ON"))

        # Migrations: add columns that may not exist yet
        try:
            await conn.execute(text("ALTER TABLE circuits ADD COLUMN live_timing_url VARCHAR(255) DEFAULT ''"))
        except Exception:
            pass  # Column already exists

        # Add ws_port_data column and populate with ws_port - 1
        try:
            await conn.execute(text("ALTER TABLE circuits ADD COLUMN ws_port_data INTEGER"))
        except Exception:
            pass  # Column already exists
        await conn.execute(text("""
            UPDATE circuits SET ws_port_data = ws_port - 1
            WHERE ws_port_data IS NULL
        """))

        # Add pit window columns to race_sessions
        try:
            await conn.execute(text("ALTER TABLE race_sessions ADD COLUMN pit_closed_start_min INTEGER DEFAULT 0"))
        except Exception:
            pass
        try:
            await conn.execute(text("ALTER TABLE race_sessions ADD COLUMN pit_closed_end_min INTEGER DEFAULT 0"))
        except Exception:
            pass

        # Recreate live_race_state if it has the old schema (race_session_id column)
        try:
            result = await conn.execute(text("PRAGMA table_info(live_race_state)"))
            columns = [row[1] for row in result.fetchall()]
            if columns and "race_session_id" in columns:
                await conn.execute(text("DROP TABLE IF EXISTS live_pit_events"))
                await conn.execute(text("DROP TABLE IF EXISTS live_race_state"))
                logger.info("Dropped old live_race_state/live_pit_events tables (schema migration)")
        except Exception:
            pass

        # Add retention_days to circuits
        try:
            await conn.execute(text("ALTER TABLE circuits ADD COLUMN retention_days INTEGER DEFAULT 30 NOT NULL"))
        except Exception:
            pass

        # Add warmup_laps_to_skip to circuits (excluded from rolling 20-lap mean)
        # Tracking module: per-circuit polyline + sectors + pit lane.
        # Each ALTER is wrapped in try/except — SQLite raises if the column
        # already exists (no IF NOT EXISTS for ALTER TABLE pre-3.35).
        for col_sql in (
            "ALTER TABLE circuits ADD COLUMN track_polyline TEXT",
            "ALTER TABLE circuits ADD COLUMN track_length_m FLOAT",
            "ALTER TABLE circuits ADD COLUMN s1_distance_m FLOAT",
            "ALTER TABLE circuits ADD COLUMN s2_distance_m FLOAT",
            "ALTER TABLE circuits ADD COLUMN s3_distance_m FLOAT",
            "ALTER TABLE circuits ADD COLUMN pit_entry_distance_m FLOAT",
            "ALTER TABLE circuits ADD COLUMN pit_exit_distance_m FLOAT",
            "ALTER TABLE circuits ADD COLUMN pit_entry_lat FLOAT",
            "ALTER TABLE circuits ADD COLUMN pit_entry_lon FLOAT",
            "ALTER TABLE circuits ADD COLUMN pit_exit_lat FLOAT",
            "ALTER TABLE circuits ADD COLUMN pit_exit_lon FLOAT",
            "ALTER TABLE circuits ADD COLUMN pit_lane_polyline TEXT",
            "ALTER TABLE circuits ADD COLUMN pit_lane_length_m FLOAT",
            "ALTER TABLE circuits ADD COLUMN pit_box_distance_m FLOAT",
            "ALTER TABLE circuits ADD COLUMN meta_distance_m FLOAT DEFAULT 0.0 NOT NULL",
            "ALTER TABLE circuits ADD COLUMN default_direction VARCHAR(16) DEFAULT 'forward' NOT NULL",
            "ALTER TABLE circuits ADD COLUMN svg_viewbox VARCHAR(64)",
            "ALTER TABLE circuits ADD COLUMN svg_paths_json TEXT",
            "ALTER TABLE circuits ADD COLUMN svg_image_url VARCHAR(2048)",
        ):
            try:
                await conn.execute(text(col_sql))
            except Exception:
                pass  # column already exists

        try:
            await conn.execute(text("ALTER TABLE circuits ADD COLUMN warmup_laps_to_skip INTEGER DEFAULT 3 NOT NULL"))
        except Exception:
            pass

        try:
            await conn.execute(text("ALTER TABLE circuits ADD COLUMN for_sale BOOLEAN NOT NULL DEFAULT 1"))
        except Exception:
            pass  # Column already exists
        try:
            await conn.execute(text("ALTER TABLE circuits ADD COLUMN is_beta BOOLEAN NOT NULL DEFAULT 0"))
        except Exception:
            pass  # Column already exists

        # Add kart_number to gps_telemetry_laps (used to sync with replay)
        try:
            await conn.execute(text("ALTER TABLE gps_telemetry_laps ADD COLUMN kart_number INTEGER"))
        except Exception:
            pass
        try:
            await conn.execute(text("CREATE INDEX IF NOT EXISTS ix_gps_telemetry_laps_kart_number ON gps_telemetry_laps (kart_number)"))
        except Exception:
            pass

        # Add recorded_at to kart_laps
        try:
            await conn.execute(text("ALTER TABLE kart_laps ADD COLUMN recorded_at DATETIME"))
        except Exception:
            pass

        # Add MFA columns to users
        try:
            await conn.execute(text("ALTER TABLE users ADD COLUMN mfa_secret VARCHAR"))
        except Exception:
            pass
        try:
            await conn.execute(text("ALTER TABLE users ADD COLUMN mfa_enabled BOOLEAN DEFAULT 0"))
        except Exception:
            pass
        try:
            await conn.execute(text("ALTER TABLE users ADD COLUMN mfa_required BOOLEAN DEFAULT 0"))
        except Exception:
            pass

        # Seed default app settings
        await conn.execute(text("""
            INSERT OR IGNORE INTO app_settings (key, value) VALUES ('kart_analytics_retention_days', '30')
        """))
        # Platform settings defaults
        for _key, _val in [("trial_days", "14"), ("trial_banner_days", "7"), ("trial_email_days", "3")]:
            await conn.execute(text(
                "INSERT OR IGNORE INTO app_settings (key, value) VALUES (:key, :value)"
            ), {"key": _key, "value": _val})

        # Seed live timing URLs for known circuits
        await conn.execute(text("""
            UPDATE circuits SET live_timing_url = 'https://www.apex-timing.com/live-timing/ariza-racing-circuit/index.html'
            WHERE id = 25 AND (live_timing_url IS NULL OR live_timing_url = '')
        """))
        await conn.execute(text("""
            UPDATE circuits SET live_timing_url = 'https://www.apex-timing.com/live-timing/karting-lossantos/index.html'
            WHERE id = 1 AND (live_timing_url IS NULL OR live_timing_url = '')
        """))


        # Add email, google_id, stripe_customer_id to users
        try:
            await conn.execute(text("ALTER TABLE users ADD COLUMN email VARCHAR(255)"))
        except Exception:
            pass
        try:
            await conn.execute(text("ALTER TABLE users ADD COLUMN google_id VARCHAR(255)"))
        except Exception:
            pass
        try:
            await conn.execute(text("ALTER TABLE users ADD COLUMN stripe_customer_id VARCHAR(255)"))
        except Exception:
            pass

        # Add password reset columns to users
        try:
            await conn.execute(text("ALTER TABLE users ADD COLUMN password_reset_token VARCHAR(255)"))
        except Exception:
            pass
        try:
            await conn.execute(text("ALTER TABLE users ADD COLUMN password_reset_expires DATETIME"))
        except Exception:
            pass

        # Seed default tab access for all users (basic tabs)
        # This ensures existing users get access to all standard tabs
        basic_tabs = ["race", "pit", "live", "adjusted", "driver", "config", "replay", "analytics"]
        for tab in basic_tabs:
            await conn.execute(text("""
                INSERT OR IGNORE INTO user_tab_access (user_id, tab)
                SELECT id, :tab FROM users WHERE id NOT IN (
                    SELECT user_id FROM user_tab_access WHERE tab = :tab
                )
            """), {"tab": tab})

        # Migrate granular tab permissions: users with parent tab get new sub-tabs
        # driver → driver-config, analytics → insights
        # (adjusted-beta retired — folded into adjusted with the time-domain
        # algorithm, no longer a separate tab.)
        tab_migrations = [
            ("driver", "driver-config"),
            ("analytics", "insights"),
        ]
        for parent_tab, new_tab in tab_migrations:
            await conn.execute(text("""
                INSERT OR IGNORE INTO user_tab_access (user_id, tab)
                SELECT user_id, :new_tab FROM user_tab_access
                WHERE tab = :parent_tab AND user_id NOT IN (
                    SELECT user_id FROM user_tab_access WHERE tab = :new_tab
                )
            """), {"parent_tab": parent_tab, "new_tab": new_tab})

        # Migrate product_tab_config: add stripe_price_id, price_amount, billing_interval columns
        try:
            await conn.execute(text("ALTER TABLE product_tab_config ADD COLUMN stripe_price_id VARCHAR(255)"))
        except Exception:
            pass
        try:
            await conn.execute(text("ALTER TABLE product_tab_config ADD COLUMN price_amount FLOAT"))
        except Exception:
            pass
        try:
            await conn.execute(text("ALTER TABLE product_tab_config ADD COLUMN billing_interval VARCHAR(20)"))
        except Exception:
            pass
        # SQLite can't DROP CONSTRAINT — recreate table to remove UNIQUE on stripe_product_id
        try:
            result = await conn.execute(text("PRAGMA index_list('product_tab_config')"))
            indexes = result.fetchall()
            has_old_unique = any(
                "stripe_product_id" in str(idx) and idx[2] == 1  # idx[2]=1 means unique
                for idx in indexes
            )
            if not has_old_unique:
                # Also check via index_info for auto-generated unique index names
                for idx in indexes:
                    if idx[2] == 1:  # unique index
                        idx_info = await conn.execute(text(f"PRAGMA index_info('{idx[1]}')"))
                        cols = [row[2] for row in idx_info.fetchall()]
                        if cols == ["stripe_product_id"]:
                            has_old_unique = True
                            break

            if has_old_unique:
                logger.info("Migrating product_tab_config: removing UNIQUE on stripe_product_id")
                await conn.execute(text("""
                    CREATE TABLE product_tab_config_new (
                        id INTEGER PRIMARY KEY AUTOINCREMENT,
                        stripe_product_id VARCHAR(255) NOT NULL,
                        stripe_price_id VARCHAR(255) NOT NULL UNIQUE,
                        plan_type VARCHAR(50) NOT NULL UNIQUE,
                        tabs TEXT NOT NULL DEFAULT '[]',
                        max_devices INTEGER NOT NULL DEFAULT 1,
                        display_name VARCHAR(100) NOT NULL DEFAULT '',
                        description TEXT,
                        features TEXT DEFAULT '[]',
                        price_amount FLOAT,
                        billing_interval VARCHAR(20),
                        is_popular BOOLEAN NOT NULL DEFAULT 0,
                        is_visible BOOLEAN NOT NULL DEFAULT 1,
                        sort_order INTEGER NOT NULL DEFAULT 0
                    )
                """))
                await conn.execute(text("""
                    INSERT INTO product_tab_config_new
                        (id, stripe_product_id, stripe_price_id, plan_type, tabs, max_devices,
                         display_name, description, features, price_amount, billing_interval,
                         is_popular, is_visible, sort_order)
                    SELECT id, stripe_product_id,
                           COALESCE(stripe_price_id, ''),
                           COALESCE(plan_type, stripe_product_id),
                           tabs, max_devices,
                           display_name, description, features,
                           COALESCE(price_amount, 0), COALESCE(billing_interval, 'month'),
                           is_popular, is_visible, sort_order
                    FROM product_tab_config
                """))
                await conn.execute(text("DROP TABLE product_tab_config"))
                await conn.execute(text("ALTER TABLE product_tab_config_new RENAME TO product_tab_config"))
                # Recreate non-unique index on stripe_product_id
                await conn.execute(text("CREATE INDEX IF NOT EXISTS ix_product_tab_config_stripe_product_id ON product_tab_config (stripe_product_id)"))
                await conn.execute(text("CREATE INDEX IF NOT EXISTS ix_product_tab_config_stripe_price_id ON product_tab_config (stripe_price_id)"))
                logger.info("product_tab_config migration complete")
        except Exception as e:
            logger.warning(f"product_tab_config migration check: {e}")

        # Seed default/trial tab configuration in app_settings
        new_settings_defaults = {
            "default_tabs": '["race","pit","live","config","adjusted","driver","driver-config"]',
            "default_max_devices": "2",
            "trial_tabs": '["race","pit","live","config","adjusted","driver","driver-config","replay","analytics","insights"]',
            "trial_max_devices": "2",
        }
        for key, default_value in new_settings_defaults.items():
            result = await conn.execute(text(f"SELECT key FROM app_settings WHERE key = :key"), {"key": key})
            if not result.fetchone():
                await conn.execute(
                    text("INSERT INTO app_settings (key, value) VALUES (:key, :value)"),
                    {"key": key, "value": default_value},
                )


        # Add pending_plan column to subscriptions
        try:
            await conn.execute(text("ALTER TABLE subscriptions ADD COLUMN pending_plan VARCHAR(50)"))
        except Exception:
            pass

        # Add auto_load_teams column to race_sessions
        try:
            await conn.execute(text("ALTER TABLE race_sessions ADD COLUMN auto_load_teams BOOLEAN DEFAULT 1 NOT NULL"))
        except Exception:
            pass

        # Add has_custom_password column to users (False for Google-only signups)
        try:
            await conn.execute(text("ALTER TABLE users ADD COLUMN has_custom_password BOOLEAN DEFAULT 1 NOT NULL"))
            # Mark existing Google-only users as not having a custom password
            await conn.execute(text(
                "UPDATE users SET has_custom_password = 0 WHERE google_id IS NOT NULL AND google_id != ''"
            ))
        except Exception:
            pass

        # Add concurrency_web, concurrency_mobile, per_circuit to product_tab_config
        try:
            await conn.execute(text("ALTER TABLE product_tab_config ADD COLUMN concurrency_web INTEGER"))
        except Exception:
            pass
        try:
            await conn.execute(text("ALTER TABLE product_tab_config ADD COLUMN concurrency_mobile INTEGER"))
        except Exception:
            pass
        try:
            await conn.execute(text("ALTER TABLE product_tab_config ADD COLUMN per_circuit BOOLEAN DEFAULT 1 NOT NULL"))
        except Exception:
            pass
        # "Venta próximamente" flag — plan announced but not yet on sale.
        try:
            await conn.execute(text("ALTER TABLE product_tab_config ADD COLUMN coming_soon BOOLEAN DEFAULT 0 NOT NULL"))
        except Exception:
            pass
        # Diagnostic: raw Apex last position on session_results (rating
        # uses reconstructed final_position; this is audit-only).
        try:
            await conn.execute(text("ALTER TABLE session_results ADD COLUMN apex_last_position INTEGER"))
        except Exception:
            pass

        # Drop UNIQUE constraint on product_tab_config.plan_type so the same
        # label can be reused across multiple products. stripe_price_id remains
        # unique (one row per price). SQLite can't DROP CONSTRAINT — detect the
        # unique index on plan_type and rebuild the table without it.
        try:
            idx_result = await conn.execute(text("PRAGMA index_list('product_tab_config')"))
            indexes = idx_result.fetchall()
            has_unique_plan_type = False
            for idx in indexes:
                if idx[2] == 1:  # unique index
                    info = await conn.execute(text(f"PRAGMA index_info('{idx[1]}')"))
                    cols = [row[2] for row in info.fetchall()]
                    if cols == ["plan_type"]:
                        has_unique_plan_type = True
                        break
            if has_unique_plan_type:
                logger.info("Migrating product_tab_config: removing UNIQUE on plan_type")
                await conn.execute(text("""
                    CREATE TABLE product_tab_config_new (
                        id INTEGER PRIMARY KEY AUTOINCREMENT,
                        stripe_product_id VARCHAR(255) NOT NULL,
                        stripe_price_id VARCHAR(255) NOT NULL UNIQUE,
                        plan_type VARCHAR(50) NOT NULL,
                        tabs TEXT NOT NULL DEFAULT '[]',
                        max_devices INTEGER NOT NULL DEFAULT 1,
                        concurrency_web INTEGER,
                        concurrency_mobile INTEGER,
                        per_circuit BOOLEAN NOT NULL DEFAULT 1,
                        display_name VARCHAR(100) NOT NULL DEFAULT '',
                        description TEXT,
                        features TEXT DEFAULT '[]',
                        price_amount FLOAT,
                        billing_interval VARCHAR(20),
                        is_popular BOOLEAN NOT NULL DEFAULT 0,
                        is_visible BOOLEAN NOT NULL DEFAULT 1,
                        sort_order INTEGER NOT NULL DEFAULT 0
                    )
                """))
                await conn.execute(text("""
                    INSERT INTO product_tab_config_new
                        (id, stripe_product_id, stripe_price_id, plan_type, tabs, max_devices,
                         concurrency_web, concurrency_mobile, per_circuit,
                         display_name, description, features, price_amount, billing_interval,
                         is_popular, is_visible, sort_order)
                    SELECT id, stripe_product_id, stripe_price_id, plan_type, tabs, max_devices,
                           concurrency_web, concurrency_mobile, COALESCE(per_circuit, 1),
                           display_name, description, features, price_amount, billing_interval,
                           is_popular, is_visible, sort_order
                    FROM product_tab_config
                """))
                await conn.execute(text("DROP TABLE product_tab_config"))
                await conn.execute(text("ALTER TABLE product_tab_config_new RENAME TO product_tab_config"))
                await conn.execute(text("CREATE INDEX IF NOT EXISTS ix_product_tab_config_stripe_product_id ON product_tab_config (stripe_product_id)"))
                await conn.execute(text("CREATE INDEX IF NOT EXISTS ix_product_tab_config_stripe_price_id ON product_tab_config (stripe_price_id)"))
                logger.info("product_tab_config UNIQUE plan_type drop complete")
        except Exception as e:
            logger.warning(f"product_tab_config plan_type unique drop: {e}")

        # Backfill stripe_price_id on subscriptions rows that were created before
        # we started persisting it on Subscription. Populate from ProductTabConfig
        # via plan_type where possible. Needed so downstream lookups (concurrency
        # limits, invoice renewals) can resolve the config without falling back
        # to plan_type matching.
        try:
            await conn.execute(text("ALTER TABLE subscriptions ADD COLUMN stripe_price_id VARCHAR(255)"))
        except Exception:
            pass
        try:
            await conn.execute(text("""
                UPDATE subscriptions
                SET stripe_price_id = (
                    SELECT p.stripe_price_id FROM product_tab_config p
                    WHERE p.plan_type = subscriptions.plan_type
                    LIMIT 1
                )
                WHERE stripe_price_id IS NULL AND plan_type IS NOT NULL
            """))
        except Exception as e:
            logger.warning(f"subscription stripe_price_id backfill: {e}")

        # Add is_default to driver_config_presets so a single preset can be
        # marked as the "default" that auto-applies when the driver view loads.
        try:
            await conn.execute(text(
                "ALTER TABLE driver_config_presets ADD COLUMN is_default BOOLEAN DEFAULT 0 NOT NULL"
            ))
        except Exception:
            pass

        # Add display-option columns (contrast / orientation / audio_enabled)
        # to driver_config_presets so the template wizard step 4 persists.
        # Each ALTER is wrapped separately because SQLite aborts on any failure.
        for ddl in (
            "ALTER TABLE driver_config_presets ADD COLUMN contrast FLOAT",
            "ALTER TABLE driver_config_presets ADD COLUMN orientation VARCHAR(16)",
            "ALTER TABLE driver_config_presets ADD COLUMN audio_enabled BOOLEAN",
        ):
            try:
                await conn.execute(text(ddl))
            except Exception:
                pass

        # Add client_kind to device_sessions so the login endpoint can enforce
        # per-kind concurrency limits (web / mobile) the same way the WS
        # endpoint does. Existing rows are backfilled to 'web' — the safer
        # default because the legacy behavior treated every session as a
        # web session for limit purposes.
        try:
            await conn.execute(text(
                "ALTER TABLE device_sessions ADD COLUMN client_kind VARCHAR(16) "
                "NOT NULL DEFAULT 'web'"
            ))
        except Exception:
            pass

        # Per-user concurrency overrides. Both optional — NULL means "fall
        # through to the subscription plan's ProductTabConfig.concurrency_*
        # and then to the legacy max_devices". Wrapped separately so one
        # failure (e.g. column already exists) doesn't abort the other.
        for ddl in (
            "ALTER TABLE users ADD COLUMN concurrency_web INTEGER",
            "ALTER TABLE users ADD COLUMN concurrency_mobile INTEGER",
        ):
            try:
                await conn.execute(text(ddl))
            except Exception:
                pass

        # "Internal" users — bypass the subscription gate (no payment) but
        # still need active circuit access to enter. Default 0 keeps every
        # existing user as a regular paying user, no behavioural change on
        # rollout.
        try:
            await conn.execute(text(
                "ALTER TABLE users ADD COLUMN is_internal BOOLEAN NOT NULL DEFAULT 0"
            ))
        except Exception:
            pass

        # Team driver count for the pit-gate feasibility check. 0 means
        # "not configured": the gate falls back to the Apex-observed
        # driver count from kart.driver_total_ms. Strategists set this
        # in advance so the gate can enforce min_driver_time_min from
        # the first stint.
        try:
            await conn.execute(text(
                "ALTER TABLE race_sessions ADD COLUMN team_drivers_count INTEGER NOT NULL DEFAULT 0"
            ))
        except Exception:
            pass

        # Per-plan whitelist of driver-view cards. Empty string ('[]')
        # is treated as "every card" by the user_out resolver so the
        # column rollout doesn't suddenly strip every existing user of
        # their pilot-view cards; admins narrow it manually from the
        # Platform → Productos UI as they refresh each plan.
        try:
            await conn.execute(text(
                "ALTER TABLE product_tab_config ADD COLUMN allowed_cards TEXT NOT NULL DEFAULT '[]'"
            ))
        except Exception:
            pass

        # Record the installed app version + platform for each device
        # session. Populated from the `X-App-Platform` / `X-App-Version`
        # request headers (mobile clients only; blank for web). Lets the
        # Admin → Usuarios panel show which build each device is on so
        # the operator can decide when to bump the minimum-required
        # version from Admin → Plataforma.
        for ddl in (
            "ALTER TABLE device_sessions ADD COLUMN app_version VARCHAR(32) NOT NULL DEFAULT ''",
            "ALTER TABLE device_sessions ADD COLUMN app_platform VARCHAR(16) NOT NULL DEFAULT ''",
        ):
            try:
                await conn.execute(text(ddl))
            except Exception:
                pass

        # Backfill: mark a user's SOLE preset as default when they have
        # exactly one preset and none are marked as default. This fixes
        # existing users who created their first preset before the
        # "auto-default on first preset" create_preset logic shipped —
        # without this, their driver view never auto-applies contrast /
        # orientation / audio because the client only applies presets
        # flagged as default.
        try:
            await conn.execute(text(
                """
                UPDATE driver_config_presets
                SET is_default = 1
                WHERE id IN (
                    SELECT p.id
                    FROM driver_config_presets p
                    WHERE p.user_id IN (
                        SELECT user_id
                        FROM driver_config_presets
                        GROUP BY user_id
                        HAVING COUNT(*) = 1
                           AND SUM(CASE WHEN is_default THEN 1 ELSE 0 END) = 0
                    )
                )
                """
            ))
        except Exception:
            pass

        # Add email_template to product_tab_config so admins can customise the
        # subscription-confirmation email body per product from the Platform panel.
        try:
            await conn.execute(text(
                "ALTER TABLE product_tab_config ADD COLUMN email_template TEXT"
            ))
        except Exception:
            pass

        # Number of circuits the buyer must pick when the plan is sold per
        # circuit (per_circuit=True). Default 1 reproduces the legacy
        # single-circuit checkout. Values > 1 unlock the multi-circuit
        # selector in the purchase flow and the webhook grants N
        # UserCircuitAccess rows for the same Stripe payment.
        try:
            await conn.execute(text(
                "ALTER TABLE product_tab_config ADD COLUMN circuits_to_select INTEGER NOT NULL DEFAULT 1"
            ))
        except Exception:
            pass

        # Waitlist table for pre-launch lead capture
        await conn.execute(text("""
            CREATE TABLE IF NOT EXISTS waitlist_entry (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                email TEXT UNIQUE NOT NULL,
                name TEXT,
                source TEXT DEFAULT 'landing',
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """))

        # ─── Usage analytics (F1 + F2 of the analytics rollout) ───
        # `Base.metadata.create_all` above already creates the three
        # tables (usage_events / visitor_identity / usage_daily) for new
        # databases. The CREATE INDEX statements below are idempotent —
        # they cover deployments where the tables existed before this
        # migration shipped (none yet, but defensive).
        await conn.execute(text("""
            CREATE INDEX IF NOT EXISTS ix_usage_events_visitor_ts
            ON usage_events (visitor_id, ts)
        """))
        await conn.execute(text("""
            CREATE INDEX IF NOT EXISTS ix_usage_events_event_type_ts
            ON usage_events (event_type, ts)
        """))
        # Unique constraint on (user_id, day, event_key) for usage_daily,
        # treating NULL user_id as a single bucket via COALESCE — SQLite's
        # default behaviour is "NULL is distinct in unique indexes", which
        # would let us insert duplicate anonymous rows.
        await conn.execute(text("""
            CREATE UNIQUE INDEX IF NOT EXISTS uq_usage_daily_user_day_event
            ON usage_daily (COALESCE(user_id, -1), day, event_key)
        """))

async def get_db():
    async with async_session() as session:
        yield session
